GET http://localhost:5001/register/users

###
GET http://localhost:5001/register/register-max

###
GET http://localhost:5001/register/propinsi

###
GET http://localhost:5001/register/kota
###

###
GET http://localhost:5001/register/kota/32

###
GET http://localhost:5001/register/upt?page=0&limit=10

###
GET http://localhost:5001/register/allupt

###
GET http://localhost:5001/register/uptbyid/

###
GET http://localhost:5001/register/traders

###
POST http://localhost:5001/register/register
Content-Type: application/json

{
    "JENIS_USAHA": "4",
    "NOMOR_KUSUKA": "123457",
    "NAMA": "PT. PERUSAHAAN MAJU MANDIRI SAKTI",
    "NPWP": "123456789012345",
    "NO_IZIN": "3333333",
    "ALAMAT": "JL. KELIMUTU NO 53",
    "PROPINSI": "1600",
    "KOTA": "1607",
    "KODEPOS": "40000",
    "TELEPON": "021",
    "EMAIL": "EMAIL",
    "EMAIL_PNBP": "EMAIL PNBP",
    "KETERANGAN": "KETERANGAN",
    "TGL_DAFTAR": "2022/10/18",
    "FILE_ID": "ZHxOQUHpfE",
    "STATUS": "1",
    "LAST_UPDATED": "2022/10/18"
}

###
POST http://localhost:5001/register/user
Content-Type: application/json

{
    "ROLE": "8",
    "KODE_TRADER": 17503,
    "USERNAME": "MILAH",
    "PASSWORD": "cc",
    "JNS_ID": "1",
    "NO_ID": "12",
    "NAMA": "MARKUS",
    "ALAMAT": "CALIFORNIA",
    "EMAIL": "kadrun@gmail.com",
    "TELEPON": "022555213",
    "JABATAN": "Kuasa Pengguna Angin",
    "KD_UNIT": "12",
    "STATUS": "0",
    "STS_LOGIN": "0",
    "DATE_LOGIN": "2024/12/12",
    "IP_LOGIN": "",
    "LAST_LOGIN": "2024/12/12",
    "DATE_CREATED": "2024/12/12",
    "USER_CREATED": 1,
    "LAST_UPDATED": "2024/12/12",
    "USER_UPDATED": 1
}

###
# GET http://localhost:5001/register/npwp/01.309.570.8-015.000
GET http://localhost:5001/register/021.024.415.8-643.000

###
GET http://localhost:5001/register/username/maman

###
GET http://localhost:5001/register/user/17551


# get layanan
###
GET http://localhost:5001/register/layanan/alllayanan

# get by id trader
###
GET http://localhost:5001/register/getlayanan/17563

# create layanan
###
POST http://localhost:5001/register/crlayanan
Content-Type: application/json

{
    "KODE_TRADER": 107,
    "KODE_LAYANAN": "1"
}

#  get trader upt
###
GET http://localhost:5001/register/gettraderupt/48


# create trader upt
###
POST http://localhost:5001/register/crtraderupt
Content-Type: application/json

{
    "KODE_TRADER": 18223,
    "KD_UNIT": "33522",
    "KODE_TRADER_LOKAL": null,
    "STATUS": "2",
    "TGL_AKTIF": "2025-02-09",
    "USER_UPDATE": 27846,
    "DATE_CREATED": "2025-02-09"
}

###
PATCH http://localhost:5001/register/uptraderupt/18223/33522
Content-Type: application/json

{
    "KODE_TRADER": 18223,
    "KD_UNIT": "33525",
    "KODE_TRADER_LOKAL": 55555,
    "STATUS": "2",
    "TGL_AKTIF": "2025-02-09",
    "USER_UPDATE": 27846,
    "DATE_CREATED": "2025-02-09"
}

#  get trader by npwp
###
GET http://localhost:5001/register/tradernpwp/01.979.694.5-503.000

#  get folder name
###
GET http://localhost:5001/register/filefolder

#  create folder name
###
POST http://localhost:5001/register/createfolder/9miXxGMMGB