GET http://localhost:5002/viewsmkhp/gethc

###
GET http://localhost:5002/viewsmkhp/gethcbyaju/AE25.0III202500600

###
GET http://localhost:5002/viewsmkhp/gethcdtl

###
GET http://localhost:5002/viewsmkhp/gethcdtlbyaju/AE25.0III202500600

###
GET http://localhost:5002/viewsmkhp/getppk

###
GET http://localhost:5002/viewsmkhp/getppkbyaju/AE04.0III202501853

###
GET http://localhost:5002/viewsmkhp/getppkmutubyaju/AE15.0III202500667

###
GET http://localhost:5002/viewsmkhp/getppkmutuareabyaju/AE04.0III202501853

###
GET http://localhost:5002/viewsmkhp/getppkcontainerbyaju/AE03.0III202500163

###
GET http://localhost:5002/viewsmkhp/getppkdtlbyaju/AE25.0III202500600
###
GET http://localhost:5002/viewsmkhp/getppkkemasanbyaju/AE03.0III202500163

###
GET http://localhost:5002/viewsmkhp/getallkemasan

###
GET http://localhost:5002/viewsmkhp/getkemasanbykd/BX

###
GET http://localhost:5002/viewsmkhp/getppkmutuprodbyaju/AE15.0III202500667"
###
GET http://localhost:5002/viewsmkhp/getuptbyaju/15.0

###
GET http://localhost:5002/viewsmkhp/getnegarabyaju/SG

###
GET http://localhost:5002/viewsmkhp/getpelabuhanbyaju/ARPBG
